Commelier/urls.py
from django.contrib import admin
from django.urls import path, include


#20220930 박소민 
from instapost import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    # 221003 최해민 instapost include추가
    path('', include('instapost.urls')),

    # 게시글 작성 url을 불러올떄
    # 127.0.0.1:8000/instapost/new_post/

    # 220930 최해민 회원가입 기능을 구현을 위해 instauser url로 보내주기
    path('', include('instauser.urls')),

]

instapost/urls.py
from turtle import update
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'instapost'
urlpatterns = [
  #20220930 박소민 
    path('index/', views.index, name= 'index'),
    path('new_post/', views.create_post, name= 'create_review'), #new_post -> create_post로 변경 (22.09.30 문규빈)
    path('<int:pk>/edit/', views.edit, name = 'edit'),
    path('<int:pk>/update/', views.update, name = 'update'),
    path('<int:pk>/update/edit', views.remove_post, name = 'remove'),

    # 221004 박소민 게시글 상세페이지 추가
    path('instapost/<int:id>', views.detail_post, name= 'detail_post'),
    
    # 221004 박소민 댓글 create url 추가
    # 여기서 달린 <int:id>는 instapost의 pk입니다.
    path('comment/<int:id>', views.create_comment, name= 'create_comment'),
    
    # 221004 최해민 댓글 delete url 추가
    path('comment/delete/<int:id>', views.delete_comment, name= 'delete_comment'),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instauser/urls.py
from django.urls import path, include
from instauser import views

# 220930 최해민 앱네임 추가
app_name = 'instauser'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name= 'login'),
    path('logout/', views.logout_view, name= 'logout'),
    path('profile/', views.profile_view, name= 'profile'),

]

  

templates/detail-page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <!-- Facebook Meta Tags / 페이스북 오픈 그래프 -->
    <meta property="og:url" content="http://kindtiger.dothome.co.kr/insta">
    <meta property="og:type" content="website">
    <meta property="og:title" content="instagram">
    <meta property="og:description" content="instagram clone">
    <meta property="og:image" content="http://kindtiger.dothome.co.kr/insta/imgs/instagram.jpeg">
    
    <!-- Twitter Meta Tags / 트위터 -->
    <meta name="twitter:card" content="instagram clone">
    <meta name="twitter:title" content="instagram">
    <meta name="twitter:description" content="instagram clone">
    <meta name="twitter:image" content="http://kindtiger.dothome.co.kr/insta/imgs/instagram.jpeg">

    <!-- Google / Search Engine Tags / 구글 검색 엔진 -->
    <meta itemprop="name" content="instagram">
    <meta itemprop="description" content="instagram clone">
    <meta itemprop="image" content="http://kindtiger.dothome.co.kr/insta/imgs/instagram.jpeg">


    <title>instagram</title>
    <link rel="stylesheet" href="../static/css/reset.css">
    <link rel="stylesheet" href="../static/css/common.css">
    <link rel="stylesheet" href="../static/css/style.css">
    <link rel="stylesheet" href="../static/css/detail-page.css">
    <link rel="shortcut icon" href="../static/imgs/instagram.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>


<section id="container">


    <header id="header">
        <section class="h_inner">

            <h1 class="logo">
                <a href="{% url 'instapost:index' %}">
                    <div class="sprite_insta_icon"></div>
                    <div>
                        <div class="sprite_write_logo"></div>
                    </div>
                </a>
            </h1>

            <div class="right_icons">
                <a href="{% url 'instapost:create_review' %}"><div class="sprite_camera_icon"></div></a>
                <!-- <a href="login.html"><div class="sprite_compass_icon"></div></a>
                <a href="follow.html"><div class="sprite_heart_icon_outline"></div></a> -->
                <a href="{% url 'instauser:profile' %}"><div class="sprite_user_icon_outline"></div></a>
            </div>
        </section>
    </header>


    <div id="main_container">

        <section class="b_inner">

            <div class="contents_box">

                <article class="contents cont01">

                    <div class="img_section">
                        <div class="trans_inner">
                            <div><img src="../ssum/{{ instapost.images.get.image }}" alt=""></div>
                        </div>
                    </div>

                    <!-- 221004 박소민, 최해민 댓글 기능구현을 위해 수정 -->
                    <div class="detail--right_box">
                        <header class="top">
                            <div class="user_container">
                                <div class="profile_img">
                                    <img src="../static/imgs/thumb.jpeg" alt="">
                                </div>
                                <div class="user_name">
                                    <div class="nick_name">{{ instapost.author.nickname }}</div>
                                    <div class="country">{{ instapost.author.username }}</div>
                                </div>
                            </div>
                            <div class="sprite_more_icon" data-name="more" onclick="location.href='{% url 'instapost:edit' instapost.id %}';">
                                <ul class="more_detail">
                                    <li>팔로우</li>
                                    <li>수정</li>
                                    <li>삭제</li>
                                </ul>
                            </div>

                        </header>
                        <!-- 221004 박소민, 최해민 댓글기능 구현 수정 -->
                        <section class="scroll_section">
                            <div class="admin_container">
                                <div class="admin"><img src="../static/imgs/thumb.jpeg" alt="user"></div>
                                <div class="comment">
                                    <span class="user_id">{{ instapost.author.nickname }}</span>{{ instapost.content }}
                                    <div class="time">{{ instapost.create_date }}</div>
                                </div>
                            </div>
                            <!-- comments = [댓글1, 댓글2, 댓글3, 댓글4 ...] -->
                            <!-- for문을 이용해서 하나씩 꺼내와줍니다. -->
                             
                            {% for comment in comments %}
                            <div class="user_container-detail">
                                <div class="user"><img src="../static/imgs/thumb02.jpg" alt="user"></div>
                                <div class="comment">
                                    <span class="user_id">{{ comment.author.nickname }}</span>{{ comment.content }}
                                    <div class="time">{{ comment.create_date | timesince }} 전<span class="try_comment">답글 달기 
                                        {% if comment.author == request.user %}
                                            <a class="my_delete" href="{% url 'instapost:delete_comment' comment.id %}">[삭제]</a>
                                        {% endif %}
                                    </span></div>
                                    
                                    <div class="icon_wrap">
                                        <div class="more_trigger">
                                            <div class="sprite_more_icon"></div>
                                        </div>
                                        <div>
                                            <div class="sprite_small_heart_icon_outline"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </section>


                        <div class="bottom_icons">
                            <div class="left_icons">
                                <div class="heart_btn">
                                    <div class="sprite_heart_icon_outline" data-name="heartbeat"></div>
                                </div>
                                <div>
                                    <div class="sprite_bubble_icon"></div>
                                </div>
                                <div>
                                    <div class="sprite_share_icon" data-name="share"></div>
                                </div>
                            </div>

                            <div class="right_icon">
                                <div class="sprite_bookmark_outline" data-name="book-mark"></div>
                            </div>
                        </div>

                        <div class="count_likes">
                            좋아요
                            <span class="count">2,351</span>
                            개
                        </div>
                        <div class="timer">{{ instapost.create_date | timesince }} 전</div>

                        <div class="commit_field">
                            <!-- 221004 박소민, 최해민 form태그 추가 -->
                            <form action="{% url 'instapost:create_comment' instapost.id %}" method="post">
                                {% csrf_token %}
                                <input type="text" placeholder="댓글달기.." name="content">
                                <button type="submit" class="btn btn-light">게시</button>
                            </form>
                        </div>



                    </div>


                </article>


            </div>


        </section>

    </div>


    <div class="del_pop">
        <div class="btn_box">
            <div class="del">삭제</div>
            <div class="cancel">취소</div>
        </div>
   </div>

</section>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<!--<script src="js/detail.js"></script>-->


</body>
</html>

templates/detail-page_1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <!-- Facebook Meta Tags / 페이스북 오픈 그래프 -->
    <meta property="og:url" content="http://kindtiger.dothome.co.kr/insta">
    <meta property="og:type" content="website">
    <meta property="og:title" content="instagram">
    <meta property="og:description" content="instagram clone">
    <meta property="og:image" content="http://kindtiger.dothome.co.kr/insta/imgs/instagram.jpeg">
    .
    <!-- Twitter Meta Tags / 트위터 -->
    <meta name="twitter:card" content="instagram clone">
    <meta name="twitter:title" content="instagram">
    <meta name="twitter:description" content="instagram clone">
    <meta name="twitter:image" content="http://kindtiger.dothome.co.kr/insta/imgs/instagram.jpeg">

    <!-- Google / Search Engine Tags / 구글 검색 엔진 -->
    <meta itemprop="name" content="instagram">
    <meta itemprop="description" content="instagram clone">
    <meta itemprop="image" content="http://kindtiger.dothome.co.kr/insta/imgs/instagram.jpeg">


    <title>instagram</title>
    <link rel="stylesheet" href="../static/css/reset.css">
    <link rel="stylesheet" href="../static/css/common.css">
    <link rel="stylesheet" href="../static/css/style.css">
    <link rel="stylesheet" href="../static/css/new_post.css">
    <link rel="shortcut icon" href="../static/imgs/instagram.png">

</head>
<body>


<section id="container">


    <header id="header">
        <section class="h_inner">

            <h1 class="logo">
                <!-- 221004 최해민 템플릿 URL연결 -->
                <a href="{% url 'instapost:index' %}">
                    <div class="sprite_insta_icon"></div>
                    <div>
                        <div class="sprite_write_logo"></div>
                    </div>
                </a>
            </h1>

            <div class="search_field">
                <input type="text" placeholder="검색" tabindex="0">

                <div class="fake_field">
                    <span class=sprite_small_search_icon></span>
                    <span>검색</span>
                </div>
            </div>


            <div class="right_icons">
                <!-- 221004 최해민 템플릿 URL연결 -->
                <a href="{% url 'instapost:create_review' %}"><div class="sprite_camera_icon"></div></a>
                <!-- <a href="login.html"><div class="sprite_compass_icon"></div></a> -->
                <!-- <a href="follow.html"><div class="sprite_heart_icon_outline"></div></a> -->
                <a href="{% url 'instauser:profile' %}"><div class="sprite_user_icon_outline"></div></a>
            </div>
        </section>
    </header>



    <div id="main_container">

        <div class="post_form_container">

            <form action="{% url 'instapost:update' instapost.pk %}"  method= "post" class="post" enctype="multipart/form-data">
                {% csrf_token %} <!--22.10.03 문규빈 암호화-->
                <div class="title">
                    NEW POST
                </div>
                <div class="preview">
                    <div class="upload">
                        <div class="post_btn">
                            <div class="plus_icon">
                                <span></span>
                                <span></span>
                            </div>
                            <p>포스트 이미지 추가</p>
                            <canvas id="imageCanvas"></canvas>
                            <!--<p><img id="img_id" src="#" style="width: 300px; height: 300px; object-fit: cover" alt="thumbnail"></p>-->
                        </div>
                    </div>
                </div>
                <p>
                    <input type="file" name="images" id="image_field" accept="image/*" value= "{{ instapost.image }}">
                </p>
                <p>
                    <textarea name="content" id="text_field" cols="50" rows="5" > {{ instapost.content }} </textarea>

                </p>
                <input class="submit_btn" type="submit" value="저장">
            </form>

        </div>

        <form action= "{% url 'instapost:remove' instapost.pk %}"method="POST" >
            {% if user.is_authenticated %}
            {% csrf_token %}
            <input class = 'remove' name="remove" type="submit" value="삭제하기">
        
            {% endif %}
        </form>   
    </div>


</section>



<script>
       var fileInput  = document.querySelector( "#id_photo" ),
           button     = document.querySelector( ".input-file-trigger" ),
           the_return = document.querySelector(".file-return");

       // Show image
       fileInput.addEventListener('change', handleImage, false);
       var canvas = document.getElementById('imageCanvas');
       var ctx = canvas.getContext('2d');


        function handleImage(e){
           var reader = new FileReader();
           reader.onload = function(event){
               var img = new Image();
               // var imgWidth =
               img.onload = function(){
                   canvas.width = 300;
                   canvas.height = 300;
                   ctx.drawImage(img,0,0,300,300);
               };
               img.src = event.target.result;
               // img.width = img.width*0.5
               // canvas.height = img.height;
           };
           reader.readAsDataURL(e.target.files[0]);
       }


</script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>Instagram</title>

    <link rel="stylesheet" href="../static/css/reset.css">
    <link rel="stylesheet" href="../static/css/common.css">
    <link rel="stylesheet" href="../static/css/style.css">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

   
</head>

<body>
    

    <section id="container">
        <header id="header">
            <section class="inner">
                <h1 class="logo">
                    <a href="{% url 'instapost:index' %}">
                        <div class="sprite_insta_icon"></div>
                        <div class="sprite_write_logo"></div>
                    </a>
                </h1>
        

                <div class="right_icons">
                    <a href="{% url 'instapost:create_review' %}">
                        <div class="sprite_camera_icon"></div>
                    </a>
                    <!-- <a href="login.html">
                        <div class="sprite_compass_icon"></div>
                    </a>
                    <a href="follow.html">
                        <div class="sprite_heart_icon_outline"></div>
                    </a> -->
                    <a href="{% url 'instauser:profile' %}">
                        <div class="sprite_user_icon_outline"></div>
                    </a>
                </div>
            </section>
        </header>

        <section id="main_container">
            <div class="inner">
                {%for instapost in post_list%}
                <div class="contents_box">
                    <article class="contents">
                        <header class="top">
                            <div class="user_container" onclick="location.href='{% url 'instauser:profile' %}';">
                                <div class="profile_img">
                                    <img src="../static/imgs/thumb.jpeg" alt="프로필이미지">
                                </div>
                                <div class="user_name">
                                    <div class="nick_name m_text">{{ instapost.author.nickname }}</div>
                                    {% if instapost.author.is_dating == "True"%}
                                    <div class="country s_text">Couple</div>
                                    {% else %}
                                    <div class="country s_text">Single</div>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="sprite_more_icon" data-name="more" onclick="location.href='{% url 'instapost:edit' instapost.id %}';">
                                <ul class="toggle_box">
                                    <li><input type="submit" class="follow" value="팔로우" data-name="follow"></li>
                                    <li>수정</li>
                                    <li>삭제</li>
                                </ul>
                            </div>
                        </header>
                        <div class="img_section">
                            <div class="trans_inner">
                                <div><img src="../ssum/{{ instapost.images.get.image }}" alt="visual01"></div>
                                <div class= "index_content">{{ instapost.content }}</div>
                            </div>
                        </div>
                        <div class="bottom_icons">
                            <div class="left_icons">
                                <div class="heart_btn">
                                    <div class="sprite_heart_icon_outline" name="39" data-name="heartbeat"></div>
                                </div>
                                <div class="sprite_bubble_icon"></div>
                                <div class="sprite_share_icon" data-name="share"></div>
                            </div>
                            <div class="right_icon">
                                <div class="sprite_bookmark_outline" data-name="bookmark"></div>
                            </div>
                        </div>
                        <!-- <div class="likes m_text">
                            좋아요
                            <span id="like-count-39">2,346</span>
                            <span id="bookmark-count-39"></span>
                            개
                        </div> -->
                        {% for comment in instapost.comments.all %}
                        <div>
                        <div class="comment_container">
                            <div class="comment" id="comment-list-ajax-post37">
                                <div class="comment-detail">
                                    <div class="nick_name m_text">{{ comment.author.nickname }}</div>
                                    <div>{{ comment.content }}</div>
                                </div>
                            </div>
                            <!-- <div class="small_heart">
                                <div class="sprite_small_heart_icon_outline"></div>
                            </div> -->
                        </div>
                        <div class="timer">{{ comment.create_date | timesince }} 전</div>
                        {% endfor %}
                        <div class="comment_field" id="add-comment-post37">
                            <form action="{% url 'instapost:create_comment' instapost.id %}" method="post">
                                {% csrf_token %}
                                <input type="text" class= "comment_box1" placeholder="댓글달기..." name="content">
                                <div class = "comment_btn">
                                <button type="submit" class="btn btn-light">게시</button>
                                </div>
                            </form>
                        </div>
                    </div>
                
                    
                </article>
                {% endfor %}
                <input type="hidden" id="page" value="1">
            </div>
        </section>
    </section>

    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="js/main.js"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>    
</body>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <!-- Facebook Meta Tags / 페이스북 오픈 그래프 -->
    <meta property="og:url" content="http://kindtiger.dothome.co.kr/insta">
    <meta property="og:type" content="website">
    <meta property="og:title" content="instagram">
    <meta property="og:description" content="instagram clone">
    <meta property="og:image" content="http://kindtiger.dothome.co.kr/insta/imgs/instagram.jpeg">
    
    <!-- Twitter Meta Tags / 트위터 -->
    <meta name="twitter:card" content="instagram clone">
    <meta name="twitter:title" content="instagram">
    <meta name="twitter:description" content="instagram clone">
    <meta name="twitter:image" content="http://kindtiger.dothome.co.kr/insta/imgs/instagram.jpeg">

    <!-- Google / Search Engine Tags / 구글 검색 엔진 -->
    <meta itemprop="name" content="instagram">
    <meta itemprop="description" content="instagram clone">
    <meta itemprop="image" content="http://kindtiger.dothome.co.kr/insta/imgs/instagram.jpeg">


    <title>instagram</title>
    <link rel="stylesheet" href="../static/css/reset.css">
    <link rel="stylesheet" href="../static/css/common.css">
    <link rel="stylesheet" href="../static/css/style.css">
    <link rel="stylesheet" href="../static/css/login.css">
    <link rel="shortcut icon" href="../static/imgs/instagram.png">

</head>


<body>


<section id="container">



    <header id="header">
        <section class="h_inner">
            <!-- 221004 최해민 템플릿 URL연결 -->
            <!-- 221004 수정) 최신욱 인스타아이콘 클릭 url 경로 변경-->
            <h1 class="logo">
                <a href="{% url 'instauser:login' %}">
                    <div class="sprite_insta_icon"></div>
                    <div>
                        <div class="sprite_write_logo"></div>
                    </div>
                </a>
            </h1>



            <!-- 221004 최해민 템플릿 URL연결 -->
            <div class="right_icons">
                <a href="{% url 'instapost:create_review' %}"><div class="sprite_camera_icon"></div></a>
                <!-- <a href="login.html"><div class="sprite_compass_icon"></div></a> -->
                <!-- <a href="follow.html"><div class="sprite_heart_icon_outline"></div></a> -->
                <a href="{% url 'instauser:login' %}"><div class="sprite_user_icon_outline"></div></a>
            </div>
        </section>
    </header>



    <div id="main_container">

        <div class="form_container">

            <div class="form">


                <h1 class="sprite_insta_big_logo title"></h1>
                <form action="{% url 'instauser:login' %}" method='post'>
                    {% csrf_token %}
                    <p class="login_user_name">
                        <label for="username">ID:</label>
                        <input type="text" name='username' id='username'>
                    </p>

                    <p class="login_user_password">
                        <label for="password">비밀번호:</label>
                        <input type="password" name='password' id='password'>
                    </p>
                    <input type="submit" value="로그인" class="submit_btn">
                </form>



            </div>

            <div class="bottom_box">
                <div>
                    <span>아이디가 없으신가요?</span><a href="/signup/">회원가입</a>
                </div>
            </div>


        </div>

    </div>


</section>


</body>
</html>

templates/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <!-- Facebook Meta Tags / 페이스북 오픈 그래프 -->
    <meta property="og:url" content="http://kindtiger.dothome.co.kr/insta">
    <meta property="og:type" content="website">
    <meta property="og:title" content="instagram">
    <meta property="og:description" content="instagram clone">
    <meta property="og:image" content="http://kindtiger.dothome.co.kr/insta/imgs/instagram.jpeg">
    .
    <!-- Twitter Meta Tags / 트위터 -->
    <meta name="twitter:card" content="instagram clone">
    <meta name="twitter:title" content="instagram">
    <meta name="twitter:description" content="instagram clone">
    <meta name="twitter:image" content="http://kindtiger.dothome.co.kr/insta/imgs/instagram.jpeg">

    <!-- Google / Search Engine Tags / 구글 검색 엔진 -->
    <meta itemprop="name" content="instagram">
    <meta itemprop="description" content="instagram clone">
    <meta itemprop="image" content="http://kindtiger.dothome.co.kr/insta/imgs/instagram.jpeg">


    <title>instagram</title>
    <link rel="stylesheet" href="/static/css/reset.css">
    <link rel="stylesheet" href="/static/css/common.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/profile.css">
    <link rel="shortcut icon" href="/static/imgs/instagram.png">


</head>

<body>


    <section id="container">

        <header id="header">
            <section class="h_inner">

                <h1 class="logo">
                    <!-- 221004 최해민 템플릿 URL연결 -->
                    <a href="{% url 'instapost:index' %}">
                        <div class="sprite_insta_icon"></div>
                        <div>
                            <div class="sprite_write_logo"></div>
                        </div>
                    </a>
                </h1>

   


                <div class="right_icons">
                    <!-- 221004 최해민 템플릿 URL연결 -->
                    <a href="{% url 'instapost:create_review' %}">
                        <div class="sprite_camera_icon"></div>
                    </a>
                    <!-- <a href="login.html"><div class="sprite_compass_icon"></div></a> -->
                    <!-- <a href="follow.html"><div class="sprite_heart_icon_outline"></div></a> -->
                    <a href="{% url 'instauser:profile' %}">
                        <div class="sprite_user_icon_outline"></div>
                    </a>
                </div>
            </section>
        </header>


        <div id="main_container">

            <section class="b_inner">

                <div class="hori_cont">
                    <div class="profile_wrap">
                        <div class="profile_img">
                            <img src="../static/imgs/somin.jpeg" alt=" ">
                        </div>
                    </div>

                    <div class="detail">
                        <div class="top">
                            <div class="user_name">{{ user.nickname }}</div>
                            <!-- 221003 최신욱, 최해민 login 확인시 띄워주는 편집기능 만들기 -->
                            {% if user.is_authenticated %}
                            <!-- <a href="#" class="profile_edit">프로필편집</a> -->
                            <a href="{% url 'instauser:logout' %}" class="logout">로그아웃</a>
                            {% endif %}
                        </div>

                        <ul class="middle">
                            {% if user.is_dating == True %}
                            <li>
                                <span>Couple</span>
                            </li>
                            {% else %}
                            <li>
                                <span>Single</span>
                            </li>
                            {% endif %}
                            <li>
                                <span>게시물</span>
                                {{ instaposts.count }}
                            </li>
                            <!-- <li>
                                <span>팔로우</span>
                                3
                            </li> -->
                        </ul>
                        <!-- <p class="about">
                            <span class="nick_name">kindtigerrr</span>
                            <span class="book_mark">bookmark</span>
                        </p> -->

                    </div>
                </div>

                <div class="mylist_contents contents_container active">
                    {% for instapost in instaposts %}
                    <div class="pic">
                        <a href="{% url 'instapost:detail_post' instapost.id %}"><img src="../ssum/{{ instapost.images.get.image }}"></a>
                    </div>
                    {% endfor %}
                </div>
            </section>
        </div>


    </section>


    <!--<script src="js/insta.js"></script>-->
    <script>



    </script>
</body>

</html>